project: dot
providers:
  google_secretmanager:
    env:
      OPENAI_API_KEY:
        path: projects/vfarcic/secrets/azure-openai-key/versions/1
      OPENAI_BASE_URL:
        path: projects/vfarcic/secrets/azure-openai-base-url/versions/1
      DEFAULT_MODEL:
        path: projects/vfarcic/secrets/azure-openai-model/versions/1
